#person:
#    lastName: zhangsan
#    age: 18
#    boss: false
#    birth: 2017/12/12
#    maps: {k1: v1,k2: 12}
#    lists:
#      - lisi
#      - zhaoliu
#    dog:
#      name: littleDog
#      age: 2
serve:
    port: 8081
spring:
    profiles:
#      active: dev
       active: prod
---
#文档线
serve:
    port: 8083
spring:
    profiles: dev
---
serve:
    port: 8084
spring:
    profiles: prod
